# Generated by Django 3.0.6 on 2020-07-08 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant_app', '0008_auto_20200627_1058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_list_candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_app.ApplicantUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('designation', models.CharField(blank=True, default='', max_length=140)),
                ('company_name', models.CharField(blank=True, default='', max_length=140)),
                ('Url_of_company', models.CharField(blank=True, default='', max_length=140)),
                ('why_join_us', models.CharField(blank=True, default='', max_length=540)),
                ('company_description', models.CharField(blank=True, max_length=540)),
                ('user', models.OneToOneField(limit_choices_to={'usertype': 'Recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='recruiteruserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=140)),
                ('company_name', models.CharField(blank=True, max_length=30, verbose_name='company name')),
                ('job_salary', models.CharField(blank=True, max_length=140, verbose_name='MONTHLY HAND IN SALARY')),
                ('job_vacancies', models.IntegerField(blank=True, default=1, verbose_name='NO. OF OPENINGS')),
                ('type_of_job', models.CharField(choices=[('full time', 'FULL TIME'), ('contract', 'CONTRACT'), ('part time', 'PART TIME'), ('internship', 'INTERNSHIP'), ('volunteer', 'VOLUNTEER'), ('temporary', 'TEMPORARY'), ('remote', 'REMOTE')], default='', max_length=35, verbose_name='TYPE OF JOB')),
                ('job_location', models.CharField(choices=[('wfh', 'Work From Home'), ('ahemdabad', 'Ahmedabad'), ('bengaluru', 'Bengaluru'), ('chennai', 'Chennai'), ('delhi', 'Delhi'), ('hydradad', 'Hyderabad'), ('jaipur', 'Jaipur'), ('kolkata', 'Kolkata'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('surat', 'Surat'), ('vishakhapatnam', 'Vishakhapatnam')], default='', max_length=35, verbose_name='JOB LOCATION')),
                ('job_requirements', models.CharField(blank=True, max_length=540)),
                ('job_info', models.CharField(blank=True, max_length=540)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Expected Hiring Date')),
                ('work_choice', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Temporary due to COVID-19', 'Temporary due to COVID-19')], default='', max_length=100, verbose_name='Does this job allow hires to work remote?')),
                ('applied_by', models.ManyToManyField(blank=True, limit_choices_to={'usertype': 'Applicant'}, related_name='applied_by', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, default='def', limit_choices_to={'usertype': 'Recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
