# Generated by Django 3.0.5 on 2020-06-16 11:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
