# Generated by Django 2.2.5 on 2020-06-23 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200616_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='company_description',
            field=models.CharField(blank=True, max_length=530, verbose_name='companydescription'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='designation',
            field=models.CharField(blank=True, max_length=30, verbose_name='designation'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='location',
            field=models.CharField(blank=True, max_length=130, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='url_of_company',
            field=models.CharField(blank=True, max_length=230, verbose_name='url of company'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='why_join_us',
            field=models.CharField(blank=True, max_length=530, verbose_name='why join us'),
        ),
        migrations.AlterField(
            model_name='profcessuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)], verbose_name='Contact Phone'),
        ),
    ]
