# Generated by Django 2.2.5 on 2020-06-23 16:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200623_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profcessuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
    ]
