# Generated by Django 2.2.5 on 2020-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200625_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
