# Generated by Django 3.0.6 on 2020-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profcessuser_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='college_description',
            field=models.CharField(blank=True, max_length=530, verbose_name='collegedescription'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='college_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='college name'),
        ),
        migrations.AddField(
            model_name='profcessuser',
            name='url_of_college',
            field=models.CharField(blank=True, max_length=230, verbose_name='url of college'),
        ),
    ]
