# Generated by Django 3.0.6 on 2020-09-12 02:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200801_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profcessuser',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profcessuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='IN'),
        ),
    ]
