# Generated by Django 2.2.5 on 2020-05-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuserprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'usertype': 'Recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantuserprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
