# Generated by Django 2.2.5 on 2020-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0003_auto_20200509_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
