# Generated by Django 3.0.5 on 2020-05-26 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0004_applicantuserprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuserprofile',
            name='cell',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)], verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='preferred_domain',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='preferred_languages',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='work_experience',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
