# Generated by Django 3.0.5 on 2020-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0005_auto_20200526_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='name',
            new_name='achievements',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='preferred_domain',
            new_name='area_of_expertise',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='preferred_languages',
            new_name='country_region',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='work_experience',
            new_name='current_position',
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='duration_of_study',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='education',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='location_of_study',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='personal_headline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='profile_summary',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='resume_headline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='school',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='working_experience_company',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='working_experience_duration',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='working_experience_location',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='working_experience_title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
