# Generated by Django 3.0.5 on 2020-06-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0006_auto_20200625_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
