# Generated by Django 3.0.5 on 2020-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0007_applicantuserprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='achievements',
            new_name='accomplishment_associated_with',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='city',
            new_name='accomplishment_associated_with1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='degree',
            new_name='accomplishment_description',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='duration_of_study',
            new_name='accomplishment_description1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='location_of_study',
            new_name='accomplishment_title',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='name',
            new_name='accomplishment_title1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='personal_headline',
            new_name='associated_with',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='profile_summary',
            new_name='associated_with1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='resume_headline',
            new_name='company_location',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='school',
            new_name='company_location1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='working_experience_company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='working_experience_duration',
            new_name='company_name1',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='working_experience_location',
            new_name='company_start_month',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='working_experience_title',
            new_name='company_start_month1',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='company_start_year',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='company_start_year1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='contact_information',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_month_of_company',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_month_of_company1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_month_of_project',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_month_of_project1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_year_of_company',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_year_of_company1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_year_of_project',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='end_year_of_project1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='experience_title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='experience_title1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='field_of_study1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issue_month',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issue_month1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issue_year',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issue_year1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issuer',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='issuer1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='location',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='location_of_school',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='location_of_school1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='pheadline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_creator',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_creator1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_description1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_name1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_url',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='project_url1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='school_degree',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='school_degree1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='school_name1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_month_of_project',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_month_of_project1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_month_of_school',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_month_of_school1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_year_of_project',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_year_of_project1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_year_of_school',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicantuserprofile',
            name='start_year_of_school1',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
