# Generated by Django 2.2.5 on 2020-07-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0009_auto_20200715_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='company_start_month',
            new_name='end_company',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='company_start_year',
            new_name='end_project',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='end_month_of_company',
            new_name='end_school',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='end_month_of_project',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='end_year_of_company',
            new_name='start_company',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='end_year_of_project',
            new_name='start_project',
        ),
        migrations.RenameField(
            model_name='applicantuserprofile',
            old_name='issue_month',
            new_name='start_school',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='issue_year',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='start_month_of_project',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='start_month_of_school',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='start_year_of_project',
        ),
        migrations.RemoveField(
            model_name='applicantuserprofile',
            name='start_year_of_school',
        ),
    ]
