# Generated by Django 3.0.8 on 2020-09-07 06:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_app', '0010_auto_20200715_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuserprofile',
            name='skill_info',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JAVA', 'JAVA'), ('CPP', 'CPP'), ('C', 'C'), ('Python', 'Python'), ('jQuery', 'jQuery'), ('Javascript', 'Javascript')], default='', max_length=540),
        ),
    ]
