# Generated by Django 3.0.6 on 2020-07-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('designation', models.CharField(blank=True, default='', max_length=140)),
                ('college_name', models.CharField(blank=True, default='', max_length=140)),
                ('url_of_college', models.CharField(blank=True, default='', max_length=140)),
                ('why_join_us', models.CharField(blank=True, default='', max_length=540)),
                ('college_description', models.CharField(blank=True, max_length=540)),
                ('user', models.OneToOneField(limit_choices_to={'usertype': 'College'}, on_delete=django.db.models.deletion.CASCADE, related_name='collegeuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
