# Generated by Django 3.0.8 on 2020-09-07 06:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_requirements',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JAVA', 'JAVA'), ('CPP', 'CPP'), ('C', 'C'), ('Python', 'Python'), ('jQuery', 'jQuery'), ('Javascript', 'Javascript')], max_length=540),
        ),
    ]
